home/urls.py
from django.urls import path
from . import views
app_name = "home"
urlpatterns = [
    path('', views.HomeView.as_view() ,name="HomeView"),
]

mcu_site/urls.py
"""
URL configuration for mcu_site project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('personaggi/', include('personaggi.urls')),
    path('productions/', include('productions.urls')),
]

# Serve media files (in dev and optional in production — solo per piccoli volumi)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serve static files solo in DEBUG (dev server)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

personaggi/urls.py
from django.urls import path
from . import views

app_name = "personaggi"
urlpatterns = [
    path('', views.PersonaggiList.as_view() ,name="PersonaggiList"),
    path('<slug:slug>/', views.PersonaggiDetail.as_view() ,name="PersonaggiDetail"),
]

productions/urls.py
from django.urls import path
from . import views

app_name = "productions"
urlpatterns = [
    path('', views.ProductionsList.as_view() ,name="ProductionsList"),
    path('<slug:slug>/', views.ProductionsDetail.as_view() ,name="ProductionsDetail"),
]

home/models.py
from django.db import models
# from django.conf import settings
from personaggi.models import Personaggi

# Create your models here.

class Home(models.Model):
    # nome = models.TextField(max_length=50)
    # sopranome = models.TextField(max_length=50)
    personaggi = models.ForeignKey(Personaggi,on_delete= models.CASCADE, null=True)
    

home/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from productions.models import Productions
# from django.db.models import Avg?

# Create your views here.
# def HomeView(request):
#     return render(request,'home/index.html')

class HomeView(TemplateView):
    template_name = "home/index.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['produzioni'] = Productions.objects.all()[0:]
        # context['fasi'] = Productions.objects.all().filter(fase = "fase")
        
        context['f1'] = Productions.objects.all().filter(fase = "Fase 1")
        context['f2'] = Productions.objects.all().filter(fase = "Fase 2")
        context['f3'] = Productions.objects.all().filter(fase = "Fase 3")
        # context['f4'] = Productions.objects.all().filter(fase = "Fase 4")
        context['fasi'] = [context['f1'],context['f2'],context['f3']]
        # print(context['fasi'])
    # print("fffff",context['fasi'])
        # context["nfasi"] = len("fasi")2
        # print("nfasi")
        return context

home/templates/home/partials/_footer.html
<!--Footer container-->
<footer class="text-center text-white" style="background-color: #0a4275">
    <div class=" p-6 flex flex-col sm:flex-row sm:gap-x-12 justify-center ">
        <!-- <div class=""> -->
            <a href="{% url 'home:HomeView' %}" class="text-xl ">Home</a>
            <a href="{% url 'personaggi:PersonaggiList' %}" class="text-xl  ">Personaggi</a>
            <a href="{% url 'productions:ProductionsList' %}" class="text-xl">Produzioni</a>
            <a href="{% url 'admin:index' %}" class=" text-sm ont-semibold">Log in <span aria-hidden="true">&rarr;</span></a>
          <!-- </div> -->
            <!-- <div class="sm:flex lg:flex-1 sm:justify-end"> -->
              <!-- <a href="{% url 'admin:index' %}" class=" text-sm ont-semibold">Log in <span aria-hidden="true">&rarr;</span></a>
            </div> -->
        
     
    </div>

    <!--Copyright section-->
    <div
      class="p-4 text-center"
      style="background-color: rgba(0, 0, 0, 0.2)">
      © 2023 Copyright:
      <span>Created By Youssef Ahmed</span>
    </div>
  </footer>

home/templates/home/partials/_hero.html
<div class="hero overflow-hidden h-[50vh] bg-[#ff0000] mx-6 flex flex-col sm:flex-row ">
    <div class="titolo pl-5 text-white text-[80px] sm:text-[100px] ">
        <h1><span class="oro">M</span>ARVEL</h1>
        <h1><span class="oro">C</span>INEMATIC</h1>
        <h1><span class="oro">U</span>NIVERSE</h1>
    </div>
    <h1 class="pl-5 text-white pb-[50px] sm:text-3xl sm:pt-[10%] sm:pl-6">Il Marvel Cinematic Universe (MCU) è una serie di film, programmi televisivi e altri media basati sui personaggi dei fumetti della Marvel Comics.</h1> 
</div>

home/templates/home/partials/_nav.html
{% load static %}
<nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
  <div class="flex lg:flex-1">
    <a href="{% url 'home:HomeView' %}" class="-m-1.5 p-1.5">
      <span class="sr-only">Your Company</span>
      <img class="h-10 w-20" src="{% static 'img/Marvel.png' %}" alt="">
    </a>
  </div>
  <div class="flex sm:hidden">
    <button type="button" class="-m-2.5 menu-button inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
      <span class="sr-only">Open main menu</span>
      <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
      </svg>
    </button>
  </div>

  <div class="menu hidden sm:flex sm:gap-x-12">
    <a href="{% url 'home:HomeView' %}" class="text-xl font-semibold leading-6 text-gray-900">Home</a>
    <a href="{% url 'personaggi:PersonaggiList' %}" class="text-xl font-semibold leading-6 text-gray-900">Personaggi</a>
    <a href="{% url 'productions:ProductionsList' %}" class="text-xl font-semibold leading-6 text-gray-900">Produzioni</a>
  </div>
    <div class="menu sm:flex lg:flex-1 sm:justify-end">
      <a href="{% url 'admin:index' %}" class=" text-sm font-semibold leading-6 text-gray-900">Log in <span aria-hidden="true">&rarr;</span></a>
    </div>
  </div>

</nav>

home/templates/home/partials/body.html
{% load static %}
{% for fase in fasi %}

    <h1 class="text-2xl mt-4 pl-6" >Fase  {{ forloop.counter }}</h1>
    <div class="slider-container flex flex-row relative w-full h-[450px] overflow-hidden">
        <!-- <div id="slider" class="transition-[0.3s] h-[400px] duration-500 flex absolute top-0 left-0 px-4 py-6 w-auto gap-4 "> -->
        <div class="slider transition-[0.3s] duration-500 flex absolute top-0 left-0 px-4 py-6 w-auto gap-2 ">
            {% for f in fase %}
                <div class="slide mx-auto flex flex-col px-5 py-12 h-[450px] w-[250px]">
                    <a href="{{ f.get_absolute_url }}">
                        <h4>{{ f.nome|linebreaksbr|truncatechars:19 }}</h4>
                        {% if f.img.url %}
                            <img class="overflow-hidden rounded-md" src="{{ f.img.url }}" alt="immagine {{ f.nome }}">
                    
                        {% else %}
                        <img class=" object-cover rounded-md h-[300px] w-[200px] " src="{% static 'media/image/notfound.jpg' %}" alt="immagine: {{ f.nome }}"  >>
                        {% endif %}
                    

                    </a>
                    
                    
                    {% for protagonista in f.protagonisti.all %}
                        {% if forloop.counter < 2 %}
                            <p class="mt-1 text-sm text-gray-500">{{ protagonista }}</p>
                        {% endif %}
                    {% endfor %}
                    <a href="{{ f.get_absolute_url }}#protagonisti"><p>altri.....</p></a>
                    
                </div>
                
            {% endfor %}
        
        </div>
        <button  class="prev-button absolute text-8xl text-red-300 translate-y-[-50%] top-[40%] left-2"><</button>
        <button  class="next-button absolute text-8xl text-red-300 translate-y-[-50%] top-[40%] right-2">></button>

    </div>

{% endfor %}


   




   